# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto-lint

on:
  push:
    branches:
      - main
      - "*/*"
  workflow_dispatch:

jobs:
  test-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Changed Files
      run: |
        results=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})
        results="${results//'%'/'%25'}"
        formated_results="${results//$'\n'/' '}"
        formated_results="${fomated_results//$'\r'/' '}"
        echo "::set-output name=CHANGED_FILES::$formated_results"
        echo "CHANGED_FILES_F=${results}" >> $GITHUB_ENV
      id: changed_files
    
    - name: Display Changed Files
      run: |
        echo '${{ env.CHANGED_FILES_F }}'
        echo '${{ steps.changed_files.outputs.CHANGED_FILES }}'
        
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        results=$(flake8 ${{ steps.changed_files.outputs.CHANGED_FILES }} --exit-zero --config=.flake8)
        results="${results//'%'/'%25'}"
        results="${results//$'\n'/'%0A'}"
        results="${results//$'\r'/'%0D'}"
        results_length=${#results}
        echo "::set-output name=flake8_results::$results"
        echo "::set-output name=results_length::$results_length"
      id: lint_run

    - name: Slack Notification
      if: steps.lint_run.outputs.results_length > 0
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Linter
        SLACK_MESSAGE: "Checked files:\n ${{ env.CHANGED_FILES_F }} \n Output:\n ${{ steps.lint_run.outputs.flake8_results }}"
        SLACK_TITLE: Lint Results
