# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto-lint

on:
  # push:
  #   branches:
  #     - main
  #     - "*/*"
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Changed Files
      run: |
        results_o=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
        results="${results_o//'%'/'%25'}"
        results="${results//$'\n'/'%0A'}"
        results="${results//$'\r'/'%0D'}"

        results_o="${results_o//'%'/'%25'}"
        results_o="${results_o//$'\n'/ }"
        results_o="${results_o//$'\r'/ }"
        # echo ${results}
        # echo ${results_o}
        echo "::set-output name=CHANGED_FILES_F::$results"
        echo "::set-output name=CHANGED_FILES::$results_o"
        
      id: changed_files
    
    - name: Display Changed Files
      run: |
        echo '${{ steps.changed_files.outputs.CHANGED_FILES_F }}'
        echo '${{ steps.changed_files.outputs.CHANGED_FILES }}'
        
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        results=$(flake8 ${{ steps.changed_files.outputs.CHANGED_FILES }} --exit-zero --config=.flake8)
        results="${results//'%'/'%25'}"
        results="${results//$'\n'/'%0A'}"
        results="${results//$'\r'/'%0D'}"
        results_length=${#results}
        echo "::set-output name=flake8_results::$results"
        echo "::set-output name=results_length::$results_length"
      id: lint_run
    
    - name: Comment on PR
      if: steps.lint_run.outputs.results_length > 0
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "## Auto Linter Output:\n ```${{ steps.lint_run.outputs.flake8_results }}```"
          })


    # - name: Slack Notification
    #   if: steps.lint_run.outputs.results_length > 0
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    #     SLACK_USERNAME: Linter
    #     SLACK_MESSAGE: "\n*Checked files:*\n ${{ steps.changed_files.outputs.CHANGED_FILES_F }} \n\n *Output:*\n ${{ steps.lint_run.outputs.flake8_results }}"
    #     SLACK_TITLE: Lint Results
